[workspace]
resolver = "2"
members = [
    "input-capture",
    "input-emulation",
    "input-event",
    "monitorhop",
    "monitorhop-ipc",
    "monitorhop-cli",
    "monitorhop-gtk",
    "monitorhop-proto",
]

[workspace.package]
version = "0.1.1"

[workspace.dependencies]
input-event = { package = "monitorhop-input-event", path = "input-event", version = "0.1.1", default-features = false }
input-capture = { package = "monitorhop-input-capture", path = "input-capture", version = "0.1.1", default-features = false }
input-emulation = { package = "monitorhop-input-emulation", path = "input-emulation", version = "0.1.1", default-features = false }
monitorhop-proto = { path = "monitorhop-proto", version = "0.1.1" }
monitorhop-ipc = { path = "monitorhop-ipc", version = "0.1.1" }
monitorhop-cli = { path = "monitorhop-cli", version = "0.1.1" }
monitorhop-gtk = { path = "monitorhop-gtk", version = "0.1.1" }

[profile.release]
codegen-units = 1
lto = "fat"
strip = true
panic = "abort"
